export const GET_ALL_CRYPTOS = 'GET_ALL_CRYPTOS';
export const SEARCH_CRYPTOCURRENCIESDB = 'SEARCH_CRYPTOCURRENCIESDB';
export const GET_DETAIL_CRYPTO =  'GET_DETAIL_CRYPTO';
export const SORT_BY_NAME =  'SORT_BY_NAME';
export const ADD_TO_FAVORITES =  'ADD_TO_FAVORITES';
